# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboard < Formula
  desc "Declarative onboarding flows for engineering teams"
  homepage "https://github.com/mihailo-pavlisin/onboarding-copilot"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.3.0/onboarding-copilot_0.3.0_darwin_amd64.tar.gz"
      sha256 "17ad9098dec6418f73bdca5d805ec3a8480f9d50808c67cc875c988b9cc80cf2"

      define_method(:install) do
        bin.install "onboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.3.0/onboarding-copilot_0.3.0_darwin_arm64.tar.gz"
      sha256 "fc2f229575b5e92c039e5fde8c1bed93860694034b1a2acb5efc477d7737b27d"

      define_method(:install) do
        bin.install "onboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.3.0/onboarding-copilot_0.3.0_linux_amd64.tar.gz"
      sha256 "f6fb5788e41419134800a73d0ba98d63dc527ef134e6923d9b0939e8331234d1"
      define_method(:install) do
        bin.install "onboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.3.0/onboarding-copilot_0.3.0_linux_arm64.tar.gz"
      sha256 "c9b1f2fa2265e5c1d2cad84b8ea812926d396beb519def093a0e3321e4528e13"
      define_method(:install) do
        bin.install "onboard"
      end
    end
  end

  test do
    system "#{bin}/onboard", "--version"
  end
end
