# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboard < Formula
  desc "Declarative onboarding flows for engineering teams"
  homepage "https://github.com/mihailo-pavlisin/onboarding-copilot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.2.0/onboarding-copilot_0.2.0_darwin_amd64.tar.gz"
      sha256 "3ebf8644faec5ffcd9902b9ef1f5005563bbefa25de781e490cc8c07d332d8a0"

      define_method(:install) do
        bin.install "onboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.2.0/onboarding-copilot_0.2.0_darwin_arm64.tar.gz"
      sha256 "e1182b8417ef2177fc3832cabb71ea077a5e51c5c055995e7052135cff30b25a"

      define_method(:install) do
        bin.install "onboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.2.0/onboarding-copilot_0.2.0_linux_amd64.tar.gz"
      sha256 "756e07b3d6fc9b58c4a1afffd9ec0915023720a50f1e955a015fd039585e1f2b"
      define_method(:install) do
        bin.install "onboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mihailo-pavlisin/onboarding-copilot/releases/download/v0.2.0/onboarding-copilot_0.2.0_linux_arm64.tar.gz"
      sha256 "cac5def713f60dddc82d860708805e4619bee37f2c1cd6ec7ca740d1c2aa86ae"
      define_method(:install) do
        bin.install "onboard"
      end
    end
  end

  test do
    system "#{bin}/onboard", "--version"
  end
end
